# Generated by Django 4.0.1 on 2022-01-17 20:48
from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="SteamScreenshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("is_naughty", models.BooleanField()),
                ("is_reported", models.BooleanField()),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
