# Generated by Django 4.0.1 on 2022-01-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steamscreenshot",
            name="id",
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
