# Generated by Django 4.0.1 on 2022-02-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0001_squashed_0007_steamscreenshot_accidental_entry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steamscreenshot",
            name="app",
            field=models.IntegerField(),
        ),
    ]
