# Generated by Django 4.0.1 on 2022-01-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0002_alter_steamscreenshot_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steamscreenshot",
            name="is_naughty",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="steamscreenshot",
            name="is_reported",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
