# Generated by Django 4.0.1 on 2022-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_alter_steamscreenshot_naughty_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamscreenshot',
            name='accidental_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steamscreenshot',
            name='ban_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
